### ISSUE TITLE
issue with installer

### ISSUE THREAD

**Issue by Impostor-syndrome** [shubhampathak/ModSecurity-NGINX-setup#1]
First of all, thanks for creating original content and putting in the work :)

I just downloaded the ubuntu LTS iso "ubuntu-18.04.4-live-server-amd64.iso"
Installed it with standard settings (made sure it installed openssh server and configured it with a static ip, during the installer)

Then setup ssh keys and apt update -y ; apt upgrade -y     

Then git cloned your repo   and followed your install instructions, and ended up with this.

**root@modsec:~# git clone https://github.com/shubhampathak/ModSecurity-NGINX-setup.git**

---> https://pastebin.com/UtbA7pZr  <---

**root@modsec:~/ModSecurity-NGINX-setup# ls**
README.md  owasp.sh  setup.sh  update.sh
**root@modsec:~/ModSecurity-NGINX-setup# ./owasp.sh** 
 Setting up OWASP Top-10 official Core Rule Set (CRS)
Cloning into 'owasp-modsecurity-crs'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 10275 (delta 0), reused 4 (delta 0), pack-reused 10265
Receiving objects: 100% (10275/10275), 3.27 MiB | 679.00 KiB/s, done.
Resolving deltas: 100% (7531/7531), done.
+ nginx -t
nginx: [emerg] dlopen() "/etc/nginx/additional_modules/ngx_http_modsecurity_module.so" failed (/etc/nginx/additional_modules/ngx_http_modsecurity_module.so: cannot open shared object file: No such file or directory) in /etc/nginx/nginx.conf:5
nginx: configuration file /etc/nginx/nginx.conf test failed
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
**root@modsec:~/ModSecurity-NGINX-setup# updatedb**
**root@modsec:~/ModSecurity-NGINX-setup# ls /etc/nginx/additional_modules/**
         **ls returned empty dir**

Can i help troubleshooting your script so it can get  up and running or am i doing something wrong ?:)

root@modsec:~/ModSecurity-NGINX-setup# nginx -V
nginx version: nginx/1.14.0 (Ubuntu)
built with OpenSSL 1.1.1  11 Sep 2018
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-GkiujU/nginx-1.14.0=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --with-http_addition_module --with-http_geoip_module=dynamic --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_sub_module --with-http_xslt_module=dynamic --with-stream=dynamic --with-stream_ssl_module --with-mail=dynamic --with-mail_ssl_module

thanks for your time.

**Comment by shubhampathak** [comment]
Hi @Impostor-syndrome, thanks for the words of appreciation.

Check the line #1968 (Pastebin) and [line 50 ](https://github.com/shubhampathak/ModSecurity-NGINX-setup/blob/master/setup.sh#L50)(setup.sh).

I think the script could not identify the Nginx version number properly, that's why it failed to install Nginx Connector module.

Try to re-run the setup.sh and let me know if it works.

**Comment by Impostor-syndrome** [comment]
sorry for the late response, I tried running the $(nginx -v 2>&1 | grep -o '[0-9.]*$') command and it seems to be coming back empty.   Could it be a matter of a change in the way nginX presents its version number?

I tried running and it comes back in the same manner unfortunately.

[edit]
removing the $ works and the version number is returned, I will edit the script and see if it works then.
nginx -v 2>&1 | grep -o '[0-9.]*'   
[/edit]

[edit2]
it seemed to work, removing the $  on ubuntu-18.04.4-live-server-amd64.iso

[/edit2]

**Comment by shubhampathak** [comment]
Thanks for letting me know. I have removed $ from the line as it was not needed.
